#region AgileEAS.NET-generated
//------------------------------------------------------------------------------
//     AgileEAS.NET应用开发平台，是基于敏捷并行开发思想以及.NET构件技术而开发的一个应用系统快速开发平台，用于帮助中小软件企业
//建立一条适合快速变化的开发团队，以达到节省开发成本、缩短开发时间，快速适应市场变化的目的。
//     AgileEAS.NET应用开发平台包含基础类库、资源管理平台、运行容器、开发辅助工具等四大部分，资源管理平台为敏捷并行开发提供了
//设计、实现、测试等开发过程的并行，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子
//功能模块按照业务功能组织成单独的程序集文件，各子系统开发完成后，由AgileEAS.NET资源管理平台进行统一的集成部署。
//
//     AgileEAS.NET SOA 中间件平台是一套免费的快速开发工具，可以不受限制的用于各种非商业开发之中，商业应用请向作者获取商业授权，
//商业授权也是免费的，但是对于非授权的商业应用视为侵权，开发人员可以参考官方网站和博客园等专业网站获取公开的技术资料，也可以向
//AgileEAS.NET官方团队请求技术支持。
//
// 官方网站：http://www.smarteas.net
// 团队网站：http://www.agilelab.cn
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由AgileEAS.NET数据模型设计工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;
using System.ComponentModel;
using System.Data;
using EAS.Data;
using EAS.Data.Access;
using EAS.Data.ORM;
using System.Runtime.Serialization;

namespace HYPDM.Entities
{
   /// <summary>
   /// 实体对象 PDM_DRAWING(图纸)。
   /// </summary>
   [Serializable()]
   [Table("dbo.PDM_DRAWING","图纸")]
   partial class PDM_DRAWING: DataEntity<PDM_DRAWING>, IDataEntity<PDM_DRAWING>
   {
       public PDM_DRAWING()
       {
       }
       
       protected PDM_DRAWING(SerializationInfo info, StreamingContext context)
           : base(info, context)
       {
       }
       
       #region O/R映射成员

       /// <summary>
       /// 图纸ID 。
       /// </summary>
       [Column("DRAWINGID","图纸ID"),DataSize(128),PrimaryKey]
       [DisplayName("图纸ID")]
       public string DRAWINGID
       {
           get;
           set;
       }

       /// <summary>
       /// 图纸类型ID 。
       /// </summary>
       [Column("DRAWINGTYPE","图纸类型ID"),DataSize(64)]
       [DisplayName("图纸类型ID")]
       public string DRAWINGTYPE
       {
           get;
           set;
       }

       /// <summary>
       /// 工作号 。
       /// </summary>
       [Column("WORKNO","工作号"),DataSize(128)]
       [DisplayName("工作号")]
       public string WORKNO
       {
           get;
           set;
       }

       /// <summary>
       /// 图纸 。
       /// </summary>
       [Column("DRAWINGNAME","图纸"),DataSize(128)]
       [DisplayName("图纸")]
       public string DRAWINGNAME
       {
           get;
           set;
       }

       /// <summary>
       /// 描述 。
       /// </summary>
       [Column("DESCRIPTION","描述"),DataSize(128)]
       [DisplayName("描述")]
       public string DESCRIPTION
       {
           get;
           set;
       }

       /// <summary>
       /// 来源 。
       /// </summary>
       [Column("SOURCE","来源"),DataSize(128)]
       [DisplayName("来源")]
       public string SOURCE
       {
           get;
           set;
       }

       /// <summary>
       /// 客户名称 。
       /// </summary>
       [Column("CUSTOMER","客户名称"),DataSize(128)]
       [DisplayName("客户名称")]
       public string CUSTOMER
       {
           get;
           set;
       }

       /// <summary>
       /// 客户项目号 。
       /// </summary>
       [Column("CUSTUMERPRONO","客户项目号"),DataSize(128)]
       [DisplayName("客户项目号")]
       public string CUSTUMERPRONO
       {
           get;
           set;
       }

       /// <summary>
       /// 图幅 。
       /// </summary>
       [Column("DRAWINGSIZE","图幅"),DataSize(64)]
       [DisplayName("图幅")]
       public string DRAWINGSIZE
       {
           get;
           set;
       }

       /// <summary>
       /// 状态 。
       /// </summary>
       [Column("STATUS","状态"),DataSize(128)]
       [DisplayName("状态")]
       public string STATUS
       {
           get;
           set;
       }

       /// <summary>
       /// 修改者 。
       /// </summary>
       [Column("LASTUPDATEUSER","修改者"),DataSize(128)]
       [DisplayName("修改者")]
       public string LASTUPDATEUSER
       {
           get;
           set;
       }

       /// <summary>
       /// 创建时间 。
       /// </summary>
       [Column("CREATEDATE","创建时间"),DataSize(128)]
       [DisplayName("创建时间")]
       public string CREATEDATE
       {
           get;
           set;
       }

       /// <summary>
       /// 备注 。
       /// </summary>
       [Column("REMARK","备注"),DataSize(128)]
       [DisplayName("备注")]
       public string REMARK
       {
           get;
           set;
       }

       /// <summary>
       /// 物理文件 。
       /// </summary>
       [Column("PHYSICALFILE","物理文件"),DataSize(128)]
       [DisplayName("物理文件")]
       public string PHYSICALFILE
       {
           get;
           set;
       }

       /// <summary>
       /// 版本 。
       /// </summary>
       [Column("VERSION","版本"),DataSize(53)]
       [DisplayName("版本")]
       public float VERSION
       {
           get;
           set;
       }

       /// <summary>
       /// 修改日期 。
       /// </summary>
       [Column("LASTUPDATEDATE","修改日期"),DataSize(128)]
       [DisplayName("修改日期")]
       public string LASTUPDATEDATE
       {
           get;
           set;
       }
       
       #endregion
   }
}
