#region AgileEAS.NET-generated
//------------------------------------------------------------------------------
//     AgileEAS.NET应用开发平台，是基于敏捷并行开发思想以及.NET构件技术而开发的一个应用系统快速开发平台，用于帮助中小软件企业
//建立一条适合快速变化的开发团队，以达到节省开发成本、缩短开发时间，快速适应市场变化的目的。
//     AgileEAS.NET应用开发平台包含基础类库、资源管理平台、运行容器、开发辅助工具等四大部分，资源管理平台为敏捷并行开发提供了
//设计、实现、测试等开发过程的并行，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子
//功能模块按照业务功能组织成单独的程序集文件，各子系统开发完成后，由AgileEAS.NET资源管理平台进行统一的集成部署。
//
//     AgileEAS.NET SOA 中间件平台是一套免费的快速开发工具，可以不受限制的用于各种非商业开发之中，商业应用请向作者获取商业授权，
//商业授权也是免费的，但是对于非授权的商业应用视为侵权，开发人员可以参考官方网站和博客园等专业网站获取公开的技术资料，也可以向
//AgileEAS.NET官方团队请求技术支持。
//
// 官方网站：http://www.smarteas.net
// 团队网站：http://www.agilelab.cn
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由AgileEAS.NET数据模型设计工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;
using System.ComponentModel;
using System.Data;
using EAS.Data;
using EAS.Data.Access;
using EAS.Data.ORM;
using System.Runtime.Serialization;

namespace HYPDM.Entities
{
   /// <summary>
   /// 实体对象 PDM_Params_DETAIL(参数值表)。
   /// </summary>
   [Serializable()]
   [Table("PDM_Params_DETAIL","参数值表")]
   partial class PDM_Params_DETAIL: DataEntity<PDM_Params_DETAIL>
   {
       public PDM_Params_DETAIL()
       {
       }
       
       protected PDM_Params_DETAIL(SerializationInfo info, StreamingContext context)
           : base(info, context)
       {
       }
       
       #region O/R映射成员

       /// <summary>
       /// MASTER_TABLE_NAME 。
       /// </summary>
       [Column("MASTER_TABLE_NAME","MASTER_TABLE_NAME"),DataSize(50),PrimaryKey]
       [DisplayName("MASTER_TABLE_NAME")]
       public string MASTER_TABLE_NAME
       {
           get;
           set;
       }

       /// <summary>
       /// PK_COL_NAME 。
       /// </summary>
       [Column("PK_COL_NAME","PK_COL_NAME"),DataSize(50)]
       [DisplayName("PK_COL_NAME")]
       public string PK_COL_NAME
       {
           get;
           set;
       }

       /// <summary>
       /// PK_VALUE 。
       /// </summary>
       [Column("PK_VALUE","PK_VALUE"),DataSize(50),PrimaryKey]
       [DisplayName("PK_VALUE")]
       public string PK_VALUE
       {
           get;
           set;
       }

       /// <summary>
       /// C1 。
       /// </summary>
       [Column("C1","C1"),DataSize(50)]
       [DisplayName("C1")]
       public string C1
       {
           get;
           set;
       }

       /// <summary>
       /// C2 。
       /// </summary>
       [Column("C2","C2"),DataSize(50)]
       [DisplayName("C2")]
       public string C2
       {
           get;
           set;
       }

       /// <summary>
       /// C3 。
       /// </summary>
       [Column("C3","C3"),DataSize(50)]
       [DisplayName("C3")]
       public string C3
       {
           get;
           set;
       }

       /// <summary>
       /// C4 。
       /// </summary>
       [Column("C4","C4"),DataSize(50)]
       [DisplayName("C4")]
       public string C4
       {
           get;
           set;
       }

       /// <summary>
       /// C5 。
       /// </summary>
       [Column("C5","C5"),DataSize(50)]
       [DisplayName("C5")]
       public string C5
       {
           get;
           set;
       }

       /// <summary>
       /// C6 。
       /// </summary>
       [Column("C6","C6"),DataSize(50)]
       [DisplayName("C6")]
       public string C6
       {
           get;
           set;
       }

       /// <summary>
       /// C7 。
       /// </summary>
       [Column("C7","C7"),DataSize(50)]
       [DisplayName("C7")]
       public string C7
       {
           get;
           set;
       }

       /// <summary>
       /// C8 。
       /// </summary>
       [Column("C8","C8"),DataSize(50)]
       [DisplayName("C8")]
       public string C8
       {
           get;
           set;
       }

       /// <summary>
       /// C9 。
       /// </summary>
       [Column("C9","C9"),DataSize(50)]
       [DisplayName("C9")]
       public string C9
       {
           get;
           set;
       }

       /// <summary>
       /// C10 。
       /// </summary>
       [Column("C10","C10"),DataSize(50)]
       [DisplayName("C10")]
       public string C10
       {
           get;
           set;
       }

       /// <summary>
       /// C11 。
       /// </summary>
       [Column("C11","C11"),DataSize(50)]
       [DisplayName("C11")]
       public string C11
       {
           get;
           set;
       }

       /// <summary>
       /// C12 。
       /// </summary>
       [Column("C12","C12"),DataSize(50)]
       [DisplayName("C12")]
       public string C12
       {
           get;
           set;
       }

       /// <summary>
       /// C13 。
       /// </summary>
       [Column("C13","C13"),DataSize(50)]
       [DisplayName("C13")]
       public string C13
       {
           get;
           set;
       }

       /// <summary>
       /// C14 。
       /// </summary>
       [Column("C14","C14"),DataSize(50)]
       [DisplayName("C14")]
       public string C14
       {
           get;
           set;
       }

       /// <summary>
       /// C15 。
       /// </summary>
       [Column("C15","C15"),DataSize(50)]
       [DisplayName("C15")]
       public string C15
       {
           get;
           set;
       }

       /// <summary>
       /// C16 。
       /// </summary>
       [Column("C16","C16"),DataSize(50)]
       [DisplayName("C16")]
       public string C16
       {
           get;
           set;
       }

       /// <summary>
       /// C17 。
       /// </summary>
       [Column("C17","C17"),DataSize(50)]
       [DisplayName("C17")]
       public string C17
       {
           get;
           set;
       }

       /// <summary>
       /// C18 。
       /// </summary>
       [Column("C18","C18"),DataSize(50)]
       [DisplayName("C18")]
       public string C18
       {
           get;
           set;
       }

       /// <summary>
       /// C19 。
       /// </summary>
       [Column("C19","C19"),DataSize(50)]
       [DisplayName("C19")]
       public string C19
       {
           get;
           set;
       }

       /// <summary>
       /// C20 。
       /// </summary>
       [Column("C20","C20"),DataSize(50)]
       [DisplayName("C20")]
       public string C20
       {
           get;
           set;
       }

       /// <summary>
       /// C21 。
       /// </summary>
       [Column("C21","C21"),DataSize(50)]
       [DisplayName("C21")]
       public string C21
       {
           get;
           set;
       }

       /// <summary>
       /// C22 。
       /// </summary>
       [Column("C22","C22"),DataSize(50)]
       [DisplayName("C22")]
       public string C22
       {
           get;
           set;
       }

       /// <summary>
       /// C23 。
       /// </summary>
       [Column("C23","C23"),DataSize(50)]
       [DisplayName("C23")]
       public string C23
       {
           get;
           set;
       }

       /// <summary>
       /// C24 。
       /// </summary>
       [Column("C24","C24"),DataSize(50)]
       [DisplayName("C24")]
       public string C24
       {
           get;
           set;
       }

       /// <summary>
       /// C25 。
       /// </summary>
       [Column("C25","C25"),DataSize(50)]
       [DisplayName("C25")]
       public string C25
       {
           get;
           set;
       }

       /// <summary>
       /// C26 。
       /// </summary>
       [Column("C26","C26"),DataSize(50)]
       [DisplayName("C26")]
       public string C26
       {
           get;
           set;
       }

       /// <summary>
       /// C27 。
       /// </summary>
       [Column("C27","C27"),DataSize(50)]
       [DisplayName("C27")]
       public string C27
       {
           get;
           set;
       }

       /// <summary>
       /// C28 。
       /// </summary>
       [Column("C28","C28"),DataSize(50)]
       [DisplayName("C28")]
       public string C28
       {
           get;
           set;
       }

       /// <summary>
       /// C29 。
       /// </summary>
       [Column("C29","C29"),DataSize(50)]
       [DisplayName("C29")]
       public string C29
       {
           get;
           set;
       }

       /// <summary>
       /// C30 。
       /// </summary>
       [Column("C30","C30"),DataSize(50)]
       [DisplayName("C30")]
       public string C30
       {
           get;
           set;
       }
       
       #endregion
   }
}
