#region AgileEAS.NET-generated
//------------------------------------------------------------------------------
//     AgileEAS.NET应用开发平台，是基于敏捷并行开发思想以及.NET构件技术而开发的一个应用系统快速开发平台，用于帮助中小软件企业
//建立一条适合快速变化的开发团队，以达到节省开发成本、缩短开发时间，快速适应市场变化的目的。
//     AgileEAS.NET应用开发平台包含基础类库、资源管理平台、运行容器、开发辅助工具等四大部分，资源管理平台为敏捷并行开发提供了
//设计、实现、测试等开发过程的并行，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子
//功能模块按照业务功能组织成单独的程序集文件，各子系统开发完成后，由AgileEAS.NET资源管理平台进行统一的集成部署。
//
//     AgileEAS.NET SOA 中间件平台是一套免费的快速开发工具，可以不受限制的用于各种非商业开发之中，商业应用请向作者获取商业授权，
//商业授权也是免费的，但是对于非授权的商业应用视为侵权，开发人员可以参考官方网站和博客园等专业网站获取公开的技术资料，也可以向
//AgileEAS.NET官方团队请求技术支持。
//
// 官方网站：http://www.smarteas.net
// 团队网站：http://www.agilelab.cn
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由AgileEAS.NET数据模型设计工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;
using System.ComponentModel;
using System.Data;
using EAS.Data;
using EAS.Data.Access;
using EAS.Data.ORM;
using System.Runtime.Serialization;

namespace HYPDM.Entities
{
    /// <summary>
    /// 实体对象 PDM_PARTS(零部件)。
    /// </summary>
    [Serializable()]
    [Table("PDM_PARTS", "零部件")]
    partial class PDM_PARTS : DataEntity<PDM_PARTS>, IDataEntity<PDM_PARTS>
    {
        public PDM_PARTS()
        {
        }

        protected PDM_PARTS(SerializationInfo info, StreamingContext context)
            : base(info, context)
        {
        }

        #region O/R映射成员

        /// <summary>
        /// 零件ID 。
        /// </summary>
        [Column("PARTSID", "零件ID"), DataSize(128), PrimaryKey]
        [DisplayName("零件ID")]
        public string PARTSID
        {
            get;
            set;
        }

        /// <summary>
        /// 单件净重 。
        /// </summary>
        [Column("SINGLENETWEIGHT", "单件净重"), DataSize(53)]
        [DisplayName("单件净重")]
        public string SINGLENETWEIGHT
        {
            get;
            set;
        }

        /// <summary>
        /// 零部件类型 。
        /// </summary>
        [Column("PARTSTYPE", "零部件类型"), DataSize(64)]
        [DisplayName("零部件类型")]
        public string PARTSTYPE
        {
            get;
            set;
        }

        /// <summary>
        /// 原材料ID 。
        /// </summary>
        [Column("MATERIAL", "原材料ID"), DataSize(64)]
        [DisplayName("原材料ID")]
        public string MATERIAL
        {
            get;
            set;
        }

        /// <summary>
        /// 图号 。
        /// </summary>
        [Column("DRAWINGID", "图号"), DataSize(128)]
        [DisplayName("图号")]
        public string DRAWINGID
        {
            get;
            set;
        }

        /// <summary>
        /// 状态 。
        /// </summary>
        [Column("STATUS", "状态"), DataSize(128)]
        [DisplayName("状态")]
        public string STATUS
        {
            get;
            set;
        }

        /// <summary>
        /// 修改者 。
        /// </summary>
        [Column("LASTUPDATEUSER", "修改者"), DataSize(128)]
        [DisplayName("修改者")]
        public string LASTUPDATEUSER
        {
            get;
            set;
        }

        /// <summary>
        /// 创建时间 。
        /// </summary>
        [Column("CREATEDATE", "创建时间"), DataSize(128)]
        [DisplayName("创建时间")]
        public string CREATEDATE
        {
            get;
            set;
        }

        /// <summary>
        /// 修改日期 。
        /// </summary>
        [Column("LASTUPDATEDATE", "修改日期"), DataSize(128)]
        [DisplayName("修改日期")]
        public string LASTUPDATEDATE
        {
            get;
            set;
        }

        /// <summary>
        /// 备注 。
        /// </summary>
        [Column("REMARK", "备注"), DataSize(128)]
        [DisplayName("备注")]
        public string REMARK
        {
            get;
            set;
        }

        /// <summary>
        /// 文档ID 。
        /// </summary>
        [Column("DOCID", "文档ID"), DataSize(128)]
        [DisplayName("文档ID")]
        public string DOCID
        {
            get;
            set;
        }

        /// <summary>
        /// 版本 。
        /// </summary>
        [Column("VERSION", "版本"), DataSize(128)]
        [DisplayName("版本")]
        public string VERSION
        {
            get;
            set;
        }

        /// <summary>
        /// 零部件编号 。
        /// </summary>
        [Column("PARTSNO", "零部件编号"), DataSize(128)]
        [DisplayName("零部件编号")]
        public string PARTSNO
        {
            get;
            set;
        }

        /// <summary>
        /// 描述 。
        /// </summary>
        [Column("DESCRIPTION", "描述"), DataSize(128)]
        [DisplayName("描述")]
        public string DESCRIPTION
        {
            get;
            set;
        }

        /// <summary>
        /// 英文描述 。
        /// </summary>
        [Column("ENGDESCRIPTION", "英文描述"), DataSize(128)]
        [DisplayName("英文描述")]
        public string ENGDESCRIPTION
        {
            get;
            set;
        }

        /// <summary>
        /// 材质 。
        /// </summary>
        [Column("TEXTURE", "材质"), DataSize(128)]
        [DisplayName("材质")]
        public string TEXTURE
        {
            get;
            set;
        }

        /// <summary>
        /// 单位ID 。
        /// </summary>
        [Column("UNIT", "单位ID"), DataSize(128)]
        [DisplayName("单位ID")]
        public string UNIT
        {
            get;
            set;
        }

        /// <summary>
        /// 表面处理 。
        /// </summary>
        [Column("SURFACETREATMENT", "表面处理"), DataSize(128)]
        [DisplayName("表面处理")]
        public string SURFACETREATMENT
        {
            get;
            set;
        }

        /// <summary>
        /// 零部件分类 。
        /// 0：半成品 1：原材料 2：工艺装备
        /// </summary>
        [Column("PARTSCLASSFICATION", "零部件分类"), DataSize(128)]
        [DisplayName("零部件分类")]
        public string PARTSCLASSFICATION
        {
            get;
            set;
        }

        /// <summary>
        /// 规格代号 。
        /// </summary>
        [Column("SPECIFICATIONCODE", "规格代号"), DataSize(128)]
        [DisplayName("规格代号")]
        public string SPECIFICATIONCODE
        {
            get;
            set;
        }

        #endregion
    }
}
