#region AgileEAS.NET-generated
//------------------------------------------------------------------------------
//     AgileEAS.NET应用开发平台，是基于敏捷并行开发思想以及.NET构件技术而开发的一个应用系统快速开发平台，用于帮助中小软件企业
//建立一条适合快速变化的开发团队，以达到节省开发成本、缩短开发时间，快速适应市场变化的目的。
//     AgileEAS.NET应用开发平台包含基础类库、资源管理平台、运行容器、开发辅助工具等四大部分，资源管理平台为敏捷并行开发提供了
//设计、实现、测试等开发过程的并行，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子
//功能模块按照业务功能组织成单独的程序集文件，各子系统开发完成后，由AgileEAS.NET资源管理平台进行统一的集成部署。
//
//     AgileEAS.NET SOA 中间件平台是一套免费的快速开发工具，可以不受限制的用于各种非商业开发之中，商业应用请向作者获取商业授权，
//商业授权也是免费的，但是对于非授权的商业应用视为侵权，开发人员可以参考官方网站和博客园等专业网站获取公开的技术资料，也可以向
//AgileEAS.NET官方团队请求技术支持。
//
// 官方网站：http://www.smarteas.net
// 团队网站：http://www.agilelab.cn
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由AgileEAS.NET数据模型设计工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;
using System.ComponentModel;
using System.Data;
using EAS.Data;
using EAS.Data.Access;
using EAS.Data.ORM;
using System.Runtime.Serialization;

namespace HYPDM.Entities
{
   /// <summary>
   /// 实体对象 PDM_PRODUCT(产品)。
   /// </summary>
   [Serializable()]
   [Table("dbo.PDM_PRODUCT","产品")]
   partial class PDM_PRODUCT: DataEntity<PDM_PRODUCT>, IDataEntity<PDM_PRODUCT>
   {
       public PDM_PRODUCT()
       {
       }
       
       protected PDM_PRODUCT(SerializationInfo info, StreamingContext context)
           : base(info, context)
       {
       }
       
       #region O/R映射成员

       /// <summary>
       /// 品号 。
       /// </summary>
       [Column("PRODUCTID","品号"),DataSize(128),PrimaryKey]
       [DisplayName("品号")]
       public string PRODUCTID
       {
           get;
           set;
       }

       /// <summary>
       /// 产品名称 。
       /// </summary>
       [Column("PRODUCTNAME","产品名称"),DataSize(128)]
       [DisplayName("产品名称")]
       public string PRODUCTNAME
       {
           get;
           set;
       }

       /// <summary>
       /// 版本 。
       /// </summary>
       [Column("VERSION","版本"),DataSize(128)]
       [DisplayName("版本")]
       public string VERSION
       {
           get;
           set;
       }

       /// <summary>
       /// 顺序 。
       /// </summary>
       [Column("SORTCODE","顺序"),DataSize(10)]
       [DisplayName("顺序")]
       public int SORTCODE
       {
           get;
           set;
       }

       /// <summary>
       /// 产品型号 。
       /// </summary>
       [Column("MODELNO","产品型号"),DataSize(128)]
       [DisplayName("产品型号")]
       public string MODELNO
       {
           get;
           set;
       }

       /// <summary>
       /// 规格/尺寸 。
       /// </summary>
       [Column("SIZE","规格/尺寸"),DataSize(128)]
       [DisplayName("规格/尺寸")]
       public string SIZE
       {
           get;
           set;
       }

       /// <summary>
       /// 材料 。
       /// </summary>
       [Column("MATERIAL","材料"),DataSize(128)]
       [DisplayName("材料")]
       public string MATERIAL
       {
           get;
           set;
       }

       /// <summary>
       /// 工艺名称 。
       /// </summary>
       [Column("TECHNAME","工艺名称"),DataSize(128)]
       [DisplayName("工艺名称")]
       public string TECHNAME
       {
           get;
           set;
       }

       /// <summary>
       /// 工艺说明、 。
       /// </summary>
       [Column("TECHINSTRUCTION","工艺说明、"),DataSize(128)]
       [DisplayName("工艺说明、")]
       public string TECHINSTRUCTION
       {
           get;
           set;
       }

       /// <summary>
       /// 品号属性 。
       /// </summary>
       [Column("PRODUCTNOATTR","品号属性"),DataSize(128)]
       [DisplayName("品号属性")]
       public string PRODUCTNOATTR
       {
           get;
           set;
       }

       /// <summary>
       /// 单位ID 。
       /// </summary>
       [Column("UNIT","单位ID"),DataSize(64)]
       [DisplayName("单位ID")]
       public string UNIT
       {
           get;
           set;
       }

       /// <summary>
       /// 性质 。
       /// </summary>
       [Column("PROPERTY","性质"),DataSize(128)]
       [DisplayName("性质")]
       public string PROPERTY
       {
           get;
           set;
       }

       /// <summary>
       /// 工作中心 。
       /// </summary>
       [Column("WORKCENTER","工作中心"),DataSize(128)]
       [DisplayName("工作中心")]
       public string WORKCENTER
       {
           get;
           set;
       }

       /// <summary>
       /// 状态 。
       /// </summary>
       [Column("PRODUCTSTATUS","状态"),DataSize(128)]
       [DisplayName("状态")]
       public string PRODUCTSTATUS
       {
           get;
           set;
       }

       /// <summary>
       /// 修改者 。
       /// </summary>
       [Column("LASTUPDATEUSER","修改者"),DataSize(128)]
       [DisplayName("修改者")]
       public string LASTUPDATEUSER
       {
           get;
           set;
       }

       /// <summary>
       /// 创建日期 。
       /// </summary>
       [Column("CREATEUSER","创建日期"),DataSize(128)]
       [DisplayName("创建日期")]
       public string CREATEDATE
       {
           get;
           set;
       }

       /// <summary>
       /// 修改时间 。
       /// </summary>
       [Column("LASTUPDATEDATE","修改时间"),DataSize(128)]
       [DisplayName("修改时间")]
       public string LASTUPDATEDATE
       {
           get;
           set;
       }

       /// <summary>
       /// 备注 。
       /// </summary>
       [Column("REMARK","备注"),DataSize(128)]
       [DisplayName("备注")]
       public string REMARK
       {
           get;
           set;
       }

       /// <summary>
       /// 图号 。
       /// </summary>
       [Column("DRAWINGID","图号"),DataSize(128)]
       [DisplayName("图号")]
       public string DRAWINGID
       {
           get;
           set;
       }

       /// <summary>
       /// 产品类型 。
       /// </summary>
       [Column("PRODUCTTYPE","产品类型"),DataSize(128)]
       [DisplayName("产品类型")]
       public string PRODUCTTYPE
       {
           get;
           set;
       }

       /// <summary>
       /// 描述 。
       /// </summary>
       [Column("DESCRIPTION","描述"),DataSize(128)]
       [DisplayName("描述")]
       public string DESCRIPTION
       {
           get;
           set;
       }

       /// <summary>
       /// 英文描述 。
       /// </summary>
       [Column("ENGDESCRIPTION","英文描述"),DataSize(128)]
       [DisplayName("英文描述")]
       public string ENGDESCRIPTION
       {
           get;
           set;
       }
       
       #endregion
   }
}
